### ISSUE TITLE
Letters work perfect at webradio list but

### ISSUE THREAD

**Issue by Emilot** [jcorporation/ympd#4]
Another small(i hope) issue is with letters.

They work at webradio list and not in directory(or file, etc...) level. Actually they work with some letters and if the results extends to another page it is blank.

Weird results :)

**Comment by jcorporation** [comment]
This is a known bug at the moment. Lettering and pagination doesn't work in combination.
I think this is a design issue of this two functions and cant work.

However I am working at the moment on new queue card and afterwards the browse card will get a redesign without this issue.

**Comment by Emilot** [comment]
Great to hear to are working to a new feature! 

A big disadvantage of ympd was the mess with the search results. It is awful. I hope you will redesign it and do it more functional in the future.

Again many thanks for this awesome gui.

**Comment by jcorporation** [comment]
What is your pain with the search results? You can open a feature request in you want to discuss this.

**Comment by jcorporation** [comment]
Will not be fixed. The Browse View will be completely redesigned.
